# Generated by Django 3.0.8 on 2020-07-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticatorStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_date', models.DateTimeField(verbose_name='date logged')),
                ('derived_secure_hash', models.CharField(max_length=300)),
            ],
        ),
    ]
