# Generated by Django 3.0.8 on 2020-07-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_authenticatorstorage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticatorstorage',
            name='derived_secure_hash',
            field=models.CharField(max_length=64),
        ),
    ]
